In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
gen1 = pd.read_csv("../data/raw/plant1_generation.csv")
weather1 = pd.read_csv("../data/raw/plant1_weather.csv")

gen2 = pd.read_csv("../data/raw/plant2_generation.csv")
weather2 = pd.read_csv("../data/raw/plant2_weather.csv")

print("All datasets loaded successfully")

All datasets loaded successfully

In [3]:
print("Plant 1 Generation")
display(gen1.head())

print("Plant 1 Weather")
display(weather1.head())

print("Plant 2 Generation")
display(gen2.head())

print("Plant 2 Weather")
display(weather2.head())

Plant 1 Generation

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0

Plant 1 Weather

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0

Plant 2 Generation

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15 00:00:00,4136001,4UPUqMRk7TRMgml,0.0,0.0,9425.000000,2.429011e+06
1,2020-05-15 00:00:00,4136001,81aHJ1q11NBPMrL,0.0,0.0,0.000000,1.215279e+09
2,2020-05-15 00:00:00,4136001,9kRcWv60rDACzjR,0.0,0.0,3075.333333,2.247720e+09
3,2020-05-15 00:00:00,4136001,Et9kgGMDl729KT4,0.0,0.0,269.933333,1.704250e+06
4,2020-05-15 00:00:00,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,3177.000000,1.994153e+07

Plant 2 Weather

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,iq8k7ZNt4Mwm3w0,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,iq8k7ZNt4Mwm3w0,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,iq8k7ZNt4Mwm3w0,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,iq8k7ZNt4Mwm3w0,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,iq8k7ZNt4Mwm3w0,26.596148,25.088210,0.0

In [4]:
print("Plant 1 Generation Info")
gen1.info()

print("\nPlant 1 Weather Info")
weather1.info()

print("\nPlant 2 Generation Info")
gen2.info()

print("\nPlant 2 Weather Info")
weather2.info()

Plant 1 Generation Info
<class 'pandas.DataFrame'>
RangeIndex: 68778 entries, 0 to 68777
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    68778 non-null  str
 1   PLANT_ID     68778 non-null  int64
 2   SOURCE_KEY   68778 non-null  str
 3   DC_POWER     68778 non-null  float64
 4   AC_POWER     68778 non-null  float64
 5   DAILY_YIELD  68778 non-null  float64
 6   TOTAL_YIELD  68778 non-null  float64
dtypes: float64(4), int64(1), str(2)
memory usage: 3.7 MB

Plant 1 Weather Info
<class 'pandas.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3182 non-null   str
 1   PLANT_ID             3182 non-null   int64
 2   SOURCE_KEY           3182 non-null   str
 3   AMBIENT_TEMPERATURE  3182 non-null   float64
 4   MODULE_TEMPERATURE   3182 non-null   float64
 5   IRRADIATION          3182 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 149.3 KB

Plant 2 Generation Info
<class 'pandas.DataFrame'>
RangeIndex: 67698 entries, 0 to 67697
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    67698 non-null  str
 1   PLANT_ID     67698 non-null  int64
 2   SOURCE_KEY   67698 non-null  str
 3   DC_POWER     67698 non-null  float64
 4   AC_POWER     67698 non-null  float64
 5   DAILY_YIELD  67698 non-null  float64
 6   TOTAL_YIELD  67698 non-null  float64
dtypes: float64(4), int64(1), str(2)
memory usage: 3.6 MB

Plant 2 Weather Info
<class 'pandas.DataFrame'>
RangeIndex: 3259 entries, 0 to 3258
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3259 non-null   str
 1   PLANT_ID             3259 non-null   int64
 2   SOURCE_KEY           3259 non-null   str
 3   AMBIENT_TEMPERATURE  3259 non-null   float64
 4   MODULE_TEMPERATURE   3259 non-null   float64
 5   IRRADIATION          3259 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 152.9 KB

In [5]:
print("Plant 1 Generation Missing Values")
print(gen1.isnull().sum())

print("\nPlant 1 Weather Missing Values")
print(weather1.isnull().sum())

print("\nPlant 2 Generation Missing Values")
print(gen2.isnull().sum())

print("\nPlant 2 Weather Missing Values")
print(weather2.isnull().sum())

Plant 1 Generation Missing Values
DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64

Plant 1 Weather Missing Values
DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

Plant 2 Generation Missing Values
DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64

Plant 2 Weather Missing Values
DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

In [6]:
print(gen1.dtypes)

print("\n")
print(weather1.dtypes)

DATE_TIME          str
PLANT_ID         int64
SOURCE_KEY         str
DC_POWER       float64
AC_POWER       float64
DAILY_YIELD    float64
TOTAL_YIELD    float64
dtype: object


DATE_TIME                  str
PLANT_ID                 int64
SOURCE_KEY                 str
AMBIENT_TEMPERATURE    float64
MODULE_TEMPERATURE     float64
IRRADIATION            float64
dtype: object

In [7]:
gen1['DATE_TIME'] = pd.to_datetime(gen1['DATE_TIME'])
weather1['DATE_TIME'] = pd.to_datetime(weather1['DATE_TIME'])

gen2['DATE_TIME'] = pd.to_datetime(gen2['DATE_TIME'])
weather2['DATE_TIME'] = pd.to_datetime(weather2['DATE_TIME'])

print("DATE_TIME converted successfully")

DATE_TIME converted successfully

C:\Users\pamup\AppData\Local\Temp\ipykernel_17276\3368059957.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  gen1['DATE_TIME'] = pd.to_datetime(gen1['DATE_TIME'])

In [8]:
print(gen1.dtypes)

print("\n")
print(weather1.dtypes)

DATE_TIME      datetime64[us]
PLANT_ID                int64
SOURCE_KEY                str
DC_POWER              float64
AC_POWER              float64
DAILY_YIELD           float64
TOTAL_YIELD           float64
dtype: object


DATE_TIME              datetime64[us]
PLANT_ID                        int64
SOURCE_KEY                        str
AMBIENT_TEMPERATURE           float64
MODULE_TEMPERATURE            float64
IRRADIATION                   float64
dtype: object

In [9]:
plant1 = pd.merge(
    gen1,
    weather1,
    on=['DATE_TIME', 'PLANT_ID'],
    how='inner'
)

print("Plant 1 merged successfully")

print("Shape:", plant1.shape)

display(plant1.head())

Plant 1 merged successfully
Shape: (68774, 11)

,DATE_TIME,PLANT_ID,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,SOURCE_KEY_y,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0

In [10]:
plant1.drop(columns=['SOURCE_KEY_y'], inplace=True)

plant1.rename(
    columns={'SOURCE_KEY_x': 'SOURCE_KEY'},
    inplace=True
)

display(plant1.head())

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0

In [11]:
plant2 = pd.merge(
    gen2,
    weather2,
    on=['DATE_TIME', 'PLANT_ID'],
    how='inner'
)

plant2.drop(columns=['SOURCE_KEY_y'], inplace=True)

plant2.rename(
    columns={'SOURCE_KEY_x': 'SOURCE_KEY'},
    inplace=True
)

print("Plant 2 merged successfully")

print("Shape:", plant2.shape)

display(plant2.head())

Plant 2 merged successfully
Shape: (67698, 10)

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15,4136001,4UPUqMRk7TRMgml,0.0,0.0,9425.000000,2.429011e+06,27.004764,25.060789,0.0
1,2020-05-15,4136001,81aHJ1q11NBPMrL,0.0,0.0,0.000000,1.215279e+09,27.004764,25.060789,0.0
2,2020-05-15,4136001,9kRcWv60rDACzjR,0.0,0.0,3075.333333,2.247720e+09,27.004764,25.060789,0.0
3,2020-05-15,4136001,Et9kgGMDl729KT4,0.0,0.0,269.933333,1.704250e+06,27.004764,25.060789,0.0
4,2020-05-15,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,3177.000000,1.994153e+07,27.004764,25.060789,0.0

In [12]:
master_df = pd.concat(
    [plant1, plant2],
    ignore_index=True
)

print("Master Dataset Created")

print("Master Shape:", master_df.shape)

display(master_df.head())

Master Dataset Created
Master Shape: (136472, 10)

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0

In [13]:
print(master_df.columns)

Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER',
       'DAILY_YIELD', 'TOTAL_YIELD', 'AMBIENT_TEMPERATURE',
       'MODULE_TEMPERATURE', 'IRRADIATION'],
      dtype='str')

In [14]:
master_df.to_csv(
    "../data/processed/master_dataset.csv",
    index=False
)

print("Master dataset saved successfully")

Master dataset saved successfully

In [15]:
print(master_df.info())

print("\nMissing Values:")
print(master_df.isnull().sum())

print("\nDataset Shape:")
print(master_df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 136472 entries, 0 to 136471
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   DATE_TIME            136472 non-null  datetime64[us]
 1   PLANT_ID             136472 non-null  int64
 2   SOURCE_KEY           136472 non-null  str
 3   DC_POWER             136472 non-null  float64
 4   AC_POWER             136472 non-null  float64
 5   DAILY_YIELD          136472 non-null  float64
 6   TOTAL_YIELD          136472 non-null  float64
 7   AMBIENT_TEMPERATURE  136472 non-null  float64
 8   MODULE_TEMPERATURE   136472 non-null  float64
 9   IRRADIATION          136472 non-null  float64
dtypes: datetime64[us](1), float64(7), int64(1), str(1)
memory usage: 10.4 MB
None

Missing Values:
DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
DC_POWER               0
AC_POWER               0
DAILY_YIELD            0
TOTAL_YIELD            0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

Dataset Shape:
(136472, 10)